### ISSUE TITLE
Is it possible to use self-trained Tesseract OCR library?

### ISSUE THREAD

**Issue by GreenEric** [ShotaOchi/imagerExtra#2]
Dear Ochi San,
Thanks for the great work. I'd been struggling with the format transition from Cimg format to the format tesseract may accept without saving the image file in advace. The imagerExtra package perfectly solves my struggling.
I would like to ask if imagerExtra::OCR() may accept my self-trained character library? I'd found some online learning material for training tesseract library, and wonder if I can apply it on imagerExtra::OCR().
Besides, I would like to look for your advice for transforming Cimg format to any format the original tesseract may accept. I just can't find the transition function anywhere.
Thanks and best regards,
Eric

**Comment by ShotaOchi** [comment]
OCR function is just a wrapper function of ocr function of tesseract package.
So, I think you can use your training data as follows although I have never used my training data before.
```
your_engine <- tesseract::tesseract(datapath = "path_to_your_training_data")
OCR(cimg_object, your_engine)
```

ocr function of tesseract package accepts the 3 types of format listed below.

* raw image
* characters that specfy a path to a image 
* a magick-image object

I'm not sure what is raw image and how to convert cimg object into raw image.

The second format has been used in imagerExtra pacakge.

You can convert cimg object into magick-image object.

A function converting cimg object into magick-image object is shown below.

https://github.com/dahtah/imager/blob/39b10fe2dea36b12d2cf12100f65babd157ffb4a/R/conversions.R#L534-553

```
#' @rdname magick
#' @param im an image of class cimg
#' @param rotate determine if rotate image to adjust orientation of image
#' @return an object of class "magick-image"
#' @export
#' @author Shota Ochi
cimg2magick <- function(im, rotate = TRUE)
{
    out <- as.array(frames(im, drop = TRUE)[[1]])
    if (spectrum(im) == 1)
    {
        out <- array(out, c(dim(im)[1], dim(im)[2], 1))
    }
    out <- magick::image_read(out)
    if (rotate)
    {
        out <- magick::image_rotate(out, 90)
    }
    out
}
```
The cimg2magick function is not in CRAN version of imager.

So, I recommend that you define the cimg2magick function in your script and then use as follows.
```
magick_image <- cimg2magick(cimg_object)
tesseract::ocr(magick_image, your_engine)
```

**Comment by GreenEric** [comment]
many thanks! it does helpful!
