### ISSUE TITLE
EqualizeADP has duplicate casting of N

### ISSUE THREAD

**Issue by EngrStudent** [ShotaOchi/imagerExtra#5]
In the function EqualizeADP, line 17 and line 27 are duplicates.  Only one is needed.

Showing lines 17 to 27.

`N <- as.integer(N)
  if (n%%2 != 1) {
    n <- as.integer(n - 1)
    warning(sprintf("n is %d. n will be used as %d because n must be odd.", 
      n + 1, n), call. = FALSE)
  }
  if (minval == maxval) {
    stop("im has only one unique value. ThresholdFuzzy can't be applied for such a image.", 
      call. = FALSE)
  }
  N <- as.integer(N)`

**Comment by ShotaOchi** [comment]
Thank you for pointing out it.
I removed the duplicated line.
